### ISSUE TITLE
Missing bundles compared to CLDR 26

### ISSUE THREAD

**Issue by rxaviers** [unicode-cldr/cldr-dates-full#1]
Hi,

There are bundles in CLDR 26 that are NOT present in either cldr-dates-modern or cldr-dates-full: https://gist.github.com/rxaviers/eec5585042d426be49e5

**Comment by JCEmmons** [comment]
Refer to the section in http://cldr.unicode.org/development/development-process/design-proposals/json-packaging regarding default content locales.  We specifically and intentionally omitted default content locales from the packaging, because they are always ( by definition ) an exact copy of the parent locale, and thus are not necessary to have a duplicate.

**Comment by rxaviers** [comment]
Awesome!

PS: I have missed that part in the documentation. Sorry about that. Wise decision and I'm glad it was done.
